apiVersion: v1
kind: Service
metadata:
  name: {{ include "ballerina-app.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "ballerina-app.name" . }}
